ObiMenagement.Web/Models/ClientContactViewModel.cs
namespace ObiMenagement.Web.Models;

public class ClientContactViewModel
{
    public int ClientId { get; set; }
    public string ClientName { get; set; }
    public int PersonId { get; set; }
    public string PersonName { get; set; }
}

ObiMenagement.Web/Models/ClientViewModel.cs
namespace ObiMenagement.Web.Models;

public class ClientViewModel
{
    public int Id { get; set; }
    public string Name { get;  set; }
    public string Notes { get;  set; }
    public string Contacts { get;  set; }
    public string Location { get;  set; }
    public int LocationId { get; set; }
}

ObiMenagement.Web/Controllers/ClientController.cs
using Microsoft.AspNetCore.Mvc;
using ObiMenagement.Core.Interfaces;
using ObiMenagement.Core.Models;
using ObiMenagement.Web.Models;

namespace ObiMenagement.Web.Controllers;

public class ClientController : Controller
{
    private readonly IClientService _clientService;

    public ClientController(IClientService clientService)
    {
        _clientService = clientService;
    }
    Client Parse(ClientViewModel model)
    {
        return new Client
        {
            Id = model.Id,
            Name = model.Name,
            Notes = model.Notes,
            Location= new Location { Id=model.LocationId}
        };
    }
    ClientViewModel Parse(Client model)
    {
        return new ClientViewModel()
        {
            Id = model.Id,
            Name = model.Name,
            Notes = model.Notes,
            LocationId=model.Location.Id,
            Location = $"{model.Location.Name}:{model.Location.City}:{model.Location.Country}"
        };
    }

    ClientContactViewModel ParseClientContact(Client model)
    {
        return new ClientContactViewModel
        {
            ClientId = model.Id,
            ClientName = model.Name
        };
    }
    ClientContact ParseClientContact(ClientContactViewModel model)
    {
        return new ClientContact()
        {
            Person = new Person(){Id = model.PersonId},
            Client = new Client(){Id = model.ClientId}
        };
    }
    public async Task<IActionResult> Index()
    {
        var result = await _clientService.GetAllAsync();
        if (!result.IsSuccessful)
        {
            ModelState.AddModelError("", result.Message);
        }
        return View(result.Result.Select(Parse));
    }

    public IActionResult Create()
    {
        var model = new ClientViewModel();
        return View(model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(ClientViewModel model)
    {
        if (ModelState.IsValid)
        {
            model.Id = 0;
            var result = await _clientService.CreateAsync(Parse(model));
            if (!result.IsSuccessful)
            {
                ModelState.AddModelError("", result.Message);
                return View(model);
            }
            return RedirectToAction("Index");
        }


        return View(model);
    }
    public async Task<IActionResult> Edit(int id)
    {
        var result = await _clientService.GetByIdAsync(id);

        if (!result.IsSuccessful)
        {
            ModelState.AddModelError("", result.Message);
            return View(new ClientViewModel());
        }

        return View(Parse(result.Result));
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(ClientViewModel model)
    {
        if (ModelState.IsValid)
        {
            var result = await _clientService.EditAsync(Parse(model));
            if (!result.IsSuccessful)
            {
                ModelState.AddModelError("", result.Message);
                return View(model);

            }
            return RedirectToAction("Index");
        }
        return View(model);

    }
    public async Task<IActionResult> Details(int id)
    {
        var response = await _clientService.GetByIdAsync(id);

        if (!response.IsSuccessful)
        {
            ModelState.AddModelError("", response.Message);
            return View(new ClientViewModel());
        }
        return View(Parse(response.Result));
    }
    public async Task<IActionResult> Delete(int id)
    {
        var response = await _clientService.DeleteAsync(id);
        return Json(new GenericViewModel
        {
            IsSuccessful = response.IsSuccessful,
            ErrorMessage = response.Message
        });
    }
    
    private ViewResult AddClientContactView(ClientContactViewModel model=null)
    {
        return View("ClientContact",model?? new ClientContactViewModel());
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="id">Client Id</param>
    /// <returns></returns>
    public async Task<IActionResult> AddContact(int id)
    {
        var response = await _clientService.GetByIdAsync(id);

        if (!response.IsSuccessful)
        {
            ModelState.AddModelError("", response.Message);
            return AddClientContactView();
        }
        return AddClientContactView(ParseClientContact(response.Result));
    }

 

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddContact(ClientContactViewModel model)
    {
        if (ModelState.IsValid)
        {
            var result = await _clientService.AddClientContacts(ParseClientContact(model));
            if (!result.IsSuccessful)
            {
                ModelState.AddModelError("", result.Message);
                return AddClientContactView(model);

            }
            return RedirectToAction("Edit",new {id=model.ClientId});
        }
        return AddClientContactView(model);

    }
    
    public async Task<IActionResult> DeleteContact(int id)
    {
        var response = await _clientService.RemoveClientContacts(id);
        return Json(new GenericViewModel
        {
            IsSuccessful = response.IsSuccessful,
            ErrorMessage = response.Message
        });
    }

    public async Task<IActionResult> GetContacts(int id)
    {
        var response = await _clientService.GetClientContacts(id);

        if (!response.IsSuccessful)
        {
            return Json(new GenericViewModel
            {
                ErrorMessage = response.Message,
                IsSuccessful = response.IsSuccessful
            });
        }
        return Json(new TableViewModel<PersonViewModel>
        {
            IsSuccessful = true,
            Items = response.Result.Select(a => PersonController.Parse(a.Person)).ToList()
        });
    }
}

ObiMenagement.Web/Controllers/JsonController.cs
using Microsoft.AspNetCore.Mvc;
using ObiMenagement.Core.Interfaces;
using ObiMenagement.Core.Models;
using ObiMenagement.Web.Models;

namespace ObiMenagement.Web.Controllers;

public class JsonController : Controller

{
    private readonly ICountryService _countryService;
    private readonly ICityService _cityService;
    private readonly IPersonService _personService;
    private readonly ITrackBaseService _trackBaseService;
    private readonly ILocationService _locationService;
    private readonly ICurrencyService _currencyService;
    private readonly IEmployeeService _employeeService;
    private readonly ITrackContainerService _trackContainerService;
    private readonly IExpenseTypeService _expenseTypeService;

    public JsonController(ICountryService countryService, ICityService cityService, IPersonService personService, 
        ITrackBaseService trackBaseService, ILocationService locationService,ICurrencyService currencyService,
        IEmployeeService employeeService,ITrackContainerService trackContainerService,IExpenseTypeService expenseTypeService)
    {
        _countryService = countryService;
        _cityService = cityService;
        _personService = personService;
        _trackBaseService = trackBaseService;
        _locationService = locationService;
        _currencyService = currencyService;
        _employeeService = employeeService;
        _trackContainerService = trackContainerService;
        _expenseTypeService = expenseTypeService;
    }
    [HttpGet]
    public async Task<IActionResult> GetCountries(string search, int page)
    {
        search ??= "";
        var serviceResponse = await _countryService.GetAllWithoutMetadataAsync();

        var result = new JsonGenericModel();
        if (serviceResponse.IsSuccessful)
        {
            result.IsSuccessful = true;
            result.Items = serviceResponse.Result.Select(a => Parse(a));
        }
        else
        {
            result.ErrorMessage = serviceResponse.Message;
        }

        return Json(result);
    }
    [HttpGet]
    public async Task<IActionResult> GetCities(string search, int page, int countryId)
    {
        search ??= "";
        var serviceResponse = await _cityService.GetAllWithoutMetadataAsync(countryId);

        var result = new JsonGenericModel();
        if (serviceResponse.IsSuccessful)
        {
            result.IsSuccessful = true;
            result.Items = serviceResponse.Result.Select(a => Parse(a));
        }
        else
        {
            result.ErrorMessage = serviceResponse.Message;
        }

        return Json(result);
    }

    [HttpGet]
    public async Task<IActionResult> GetPersons(string search, int page)
    {
        search ??= "";

        var serviceResponse = await _personService.GetAllWithoutMetadataAsync();

        var result = new JsonGenericModel();
        if (serviceResponse.IsSuccessful)
        {
            result.IsSuccessful = true;
            result.Items = serviceResponse.Result.Select(a => Parse(a)).Where(a => a.Text.Contains(search));
        }
        else
        {
            result.ErrorMessage = serviceResponse.Message;
        }

        return Json(result);
    }

    [HttpGet]
    public async Task<IActionResult> GetTruckBases(string search, int page)
    {
        search ??= "";
        var serviceResponse = await _trackBaseService.GetAllAsync();

        var result = new JsonGenericModel();
        if (serviceResponse.IsSuccessful)
        {
            result.IsSuccessful = true;
            result.Items = serviceResponse.Result.Select(a => Parse(a));
        }
        else
        {
            result.ErrorMessage = serviceResponse.Message;
        }

        return Json(result);
    }
    [HttpGet]
    public async Task<IActionResult> GetTruckContainers(string search, int page)
    {
        search ??= "";
        var serviceResponse = await _trackContainerService.GetAllAsync();

        var result = new JsonGenericModel();
        if (serviceResponse.IsSuccessful)
        {
            result.IsSuccessful = true;
            result.Items = serviceResponse.Result.Select(a => Parse(a));
        }
        else
        {
            result.ErrorMessage = serviceResponse.Message;
        }

        return Json(result);
    }

    [HttpGet]
    public async Task<IActionResult> GetLocations(string search, int page)
    {
        search ??= "";
        var serviceResponse = await _locationService.GetAllAsync();

        var result = new JsonGenericModel();
        if (serviceResponse.IsSuccessful)
        {
            result.IsSuccessful = true;
            result.Items = serviceResponse.Result.Select(a => Parse(a)).Where(a => a.Text.Contains(search)).ToList();
        }
        else
        {
            result.ErrorMessage = serviceResponse.Message;
        }

        return Json(result);
    }

    [HttpGet]
    public async Task<IActionResult> GetPaymentTypes(string search, int page)
    {
        search ??= "";

        var allTypes = Enum.GetValues(typeof(PaymentTypeEnum)).Cast<PaymentTypeEnum>().Select(a => new SelectDataDTO
        {

            Id = ((int)a).ToString(),
            Text = a.ToString()
        }).ToList();

        var result = new JsonGenericModel() { IsSuccessful = true };
        result.Items = allTypes.Where(a => a.Text.Contains(search));
        return Json(result);
    }

    [HttpGet]
    public async Task<IActionResult> GetCurrencies(string search, int page)
    {
        search ??= "";
        var serviceResponse = await _currencyService.GetAllAsync();

        var result = new JsonGenericModel();
        if (serviceResponse.IsSuccessful)
        {
            result.IsSuccessful = true;
            result.Items = serviceResponse.Result.Select(a => Parse(a)).Where(a => a.Text.Contains(search)).ToList();
        }
        else
        {
            result.ErrorMessage = serviceResponse.Message;
        }

        return Json(result);
    }
    
    [HttpGet]
    public async Task<IActionResult> GetEmployees(string search, int page)
    {
        search ??= "";
        var serviceResponse = await _employeeService.GetAllAsync();

        var result = new JsonGenericModel();
        if (serviceResponse.IsSuccessful)
        {
            result.IsSuccessful = true;
            result.Items = serviceResponse.Result.Select(a => Parse(a)).Where(a => a.Text.Contains(search)).ToList();
        }
        else
        {
            result.ErrorMessage = serviceResponse.Message;
        }

        return Json(result);
    }


    [HttpGet]
    public async Task<IActionResult> GetExpenseTypes(string search, int page)
    {
        search ??= "";
        var serviceResponse = await _expenseTypeService.GetAllAsync();

        var result = new JsonGenericModel();
        if (serviceResponse.IsSuccessful)
        {
            result.IsSuccessful = true;
            result.Items = serviceResponse.Result.Select(a => Parse(a)).Where(a => a.Text.Contains(search)).ToList();
        }
        else
        {
            result.ErrorMessage = serviceResponse.Message;
        }

        return Json(result);
    }
    private SelectDataDTO Parse(ExpenseType model)
    {
        return new SelectDataDTO()
        {
            Id = model.Id.ToString(),
            Text = model.Name.ToString()
        };
    }
    private SelectDataDTO Parse(TruckContainer model)
    {
        return new SelectDataDTO()
        {
            Id = model.Id.ToString(),
            Text = model.Plate.ToString()
        };
    }
    private SelectDataDTO Parse(Employee model)
    {
        return new SelectDataDTO()
        {
            Id = model.Id.ToString(),
            Text = model.ToString()
        };
    }
    private SelectDataDTO Parse(Currency model)
    {
        return new SelectDataDTO()
        {
            Id = model.Id.ToString(),
            Text = model.Name
        };
    }
    private SelectDataDTO Parse(Location model)
    {
        return new SelectDataDTO()
        {
            Id = model.Id.ToString(),
            Text = model.ToString()
        };
    }
    private SelectDataDTO Parse(Person model)
    {
        return new SelectDataDTO()
        {
            Id = model.Id.ToString(),
            Text = model.Name
        };
    }
    private SelectDataDTO Parse(TruckBase model)
    {
        return new SelectDataDTO()
        {
            Id = model.Id.ToString(),
            Text = model.Plate
        };
    }
    private SelectDataDTO Parse(City model)
    {
        return new SelectDataDTO()
        {
            Id = model.Id.ToString(),
            Text = model.Name
        };
    }
    private SelectDataDTO Parse(Country country)
    {
        return new SelectDataDTO()
        {
            Id = country.Id.ToString(),
            Text = country.Name
        };
    }
}

ObiMenagement.Web/Views/Client/ClientContact.cshtml
@model ClientContactViewModel

@{
    ViewData["Title"] = "Create";
}

<div class="row ">
    <div class="col-md-11">
        <h2 class="d-inline">ClientContacts - @ViewData["Title"]</h2>
    </div>
    <div class="col-md-1">
        <a asp-action="Edit" asp-route-id="@Model.ClientId" class="btn btn-light">Back</a>
    </div>
</div>
<hr/>
<div class="list-header"></div>

<div class="row">
    <div class="col-md-4">
        <form asp-action="AddContact">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="ClientId" hidden/>
            <input asp-for="PersonName" value="a" hidden/>
            <div class="form-group">
                <label asp-for="ClientName" class="control-label"></label>
                <input asp-for="ClientName" disabled="disabled" class="form-control"/>
                <input asp-for="ClientName" hidden/>
                <span asp-validation-for="ClientName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PersonId" class="control-label"></label>
                <select asp-for="PersonId" class="form-control selectAdd">
                    @if (Model.PersonId > 0)
                    {
                        <option selected value="@Model.PersonId">@Model.PersonName</option>
                    }
                </select>
                <span asp-validation-for="PersonId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success"/>

            </div>
        </form>
    </div>
</div>

@section Scripts{

    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet"/>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    <script>
    $(function () {

$('#PersonId').select2({
                placeholder: 'Select an option',
                ajax: {
                    url: '@Url.Action("GetPersons", "Json")',
                    data: function (params) {
                        var query = {
                            search: params.term,
                            page: params.page || 1
                        }
                        return query;
                    },
                    processResults: function (data) {
                        return {
                            results: data.items
                        };
                    }
                }
           });
    });

</script>
}

ObiMenagement.Web/Views/Client/Create.cshtml
@model ClientViewModel

@{
    ViewData["Title"] = "Create";
}

<partial name="_header" />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <partial name="_form" model=@Model />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

@section Scripts{
<link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
<script>
    $(function () {
       $('#LocationId').select2({
            placeholder: 'Select an option',
            ajax: {
                url: '@Url.Action("GetLocations", "Json")',
                data: function (params) {
                    var query = {
                        search: params.term,
                        page: params.page || 1
                    }
                    return query;
                },
                processResults: function (data) {
                    return {
                        results: data.items
                    };
                }
            }
       });

    });
</script>
}

ObiMenagement.Web/Views/Client/Details.cshtml
@model ClientViewModel

@{
    ViewData["Title"] = "Details";
}

<partial name="_header"/>

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Notes)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
         <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Contacts)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Contacts)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" class=" btn btn-primary">Edit </a>
</div>

ObiMenagement.Web/Views/Client/Edit.cshtml
@model ClientViewModel

@{
    ViewData["Title"] = "Edit";
}

<partial name="_header" />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <partial name="_form" model=@Model />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
                <a asp-action="Delete" asp-route-id="@Model.Id" data-bs-toggle="modal" data-bs-target="#confirm-delete" class="btn btn-danger delete">Delete </a>
            </div>
        </form>
    </div>
</div>

<div class="list-header"></div>
<div class="row ">
    <div class="col-md-11">
        <h3 class="d-inline">Client  </h3>
    </div>
    <div class="col-md-1">
        <a asp-action="AddContact" asp-route-id="@Model.Id" class="btn btn-primary">Add </a>
    </div>
</div>
<hr />
<div class="list-header"></div>

<div class="row">
    <div class="col-md-12">
        <table class="table display">
            <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        LastName
                    </th>
                    <th>
                        Telephone
                    </th>
                    <th>
                        Email
                    </th>
                    <th class="no-sort">Actions</th>
                </tr>
            <tbody></tbody>
        </table>
    </div>
</div>

<div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                Delete Item
            </div>
            <div class="modal-body">
                Are you sure you want to delete this item ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancel</button>
                <a class="btn btn-danger btn-ok">Delete</a>
            </div>
        </div>
    </div>
</div>

<div class="modal" id="remove-contact-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Remove Site</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label id="RemoveModalErrorMessage" class="alert-danger"> this is a error </label>
                    </div>
                    <div class="form-group">
                        Are you sure you want to remove this site ?
                    </div>

                </form>
            </div>


            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" id="confirmRemoveContact" class="btn btn-danger">Remove</button>
            </div>
        </div>
    </div>
</div>


@section Scripts{

<link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
<link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>

<script>
    $(function () {
               var table = $(".table").DataTable({
                ajax: {
                    url: "@Url.Action("GetContacts","Client",new { id=Model.Id})",
                    dataSrc: 'items'
                },
                "columns": [
                    { "data": "name" },
                    { "data": "lastName" },
                    { "data": "phoneNumber" },
                    { "data": "email" },
                    { "data": "id" }
                ],
                "columnDefs":
                    [
                        { targets: 'no-sort', orderable: false },
                        {
                            targets: 4, render: function (data) {
                                    return " " + '<button  type="button" data-site-id="' + data + '"  class="btn btn-danger removeContact" >Remove Contact</button>'

                            }
                        }
                    ]
            });

        $('#confirm-delete').on('show.bs.modal', function (e) {
            $(".modal-body").empty().html(" Are you sure you want to delete this item ?");
           var url= $(e.relatedTarget).attr('href');
            $(this).find('.btn-ok').attr('href',url);
        });

        $(".btn-ok").on("click", function (event) {
            event.preventDefault();
            var url = $(this).attr("href");
            $.ajax
                ({
                    type: "POST",
                    url: url,
                    success: function (data) {
                        console.log(data);
                        if (data.isSuccessful) {
                             window.location.href='@Url.Action("Index")';
                        }
                        else {
                            $(".modal-body").empty().html(data.errorMessage);
                        }
                    }
                });
            return false;
        });


           
            $(".table").on("click", ".removeContact", function (e) {
                var id = $(this).attr("data-site-id");

                $("#confirmRemoveContact").attr("data-dep-id", id);
                $("#RemoveModalErrorMessage").hide();
                $('#remove-contact-modal').modal("show");
            });

            $("#confirmRemoveContact").on("click", function (event) {
                event.preventDefault();

                var id = $(this).attr("data-dep-id");

                $.ajax
                    ({
                        type: "POST",
                        url: "@Url.Action("DeleteContact", "Client")",
                        data: {
                            id: id
                        },
                        success: function (data) {
                            console.log(data);
                            if (data.isSuccessful) {
                                $("#remove-contact-modal").modal('hide');
                                table.ajax.reload();
                            }
                            else {
                                $("#RemoveModalErrorMessage").empty().html(data.errorMessage).show();
                            }
                        }
                    });
                return false;
            });
       $('#LocationId').select2({
            placeholder: 'Select an option',
            ajax: {
                url: '@Url.Action("GetLocations", "Json")',
                data: function (params) {
                    var query = {
                        search: params.term,
                        page: params.page || 1
                    }
                    return query;
                },
                processResults: function (data) {
                    return {
                        results: data.items
                    };
                }
            }
       });
    });

</script>
}

ObiMenagement.Web/Views/Client/_form.cshtml
@model ClientViewModel

<input asp-for="Id" hidden />
<input asp-for="Contacts" value="a" hidden />
<input asp-for="Location" value="a" hidden />
<div class="form-group">
    <label asp-for="Name" class="control-label"></label>
    <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Location" class="control-label"></label>
    <select asp-for="LocationId" class="form-control selectAdd">
        @if (Model.LocationId > 0)
        {
            <option selected value="@Model.LocationId">@Model.Location</option>
        }
    </select>
    <span asp-validation-for="LocationId" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Notes" class="control-label"></label>
    <textarea asp-for="Notes" class="form-control"> </textarea>
    <span asp-validation-for="Notes" class="text-danger"></span>
</div>

ObiMenagement.Web/Views/Client/_header.cshtml
<div class="row ">
    <div class="col-md-11">
        <h2 class="d-inline">Clients - @ViewData["Title"]</h2>
    </div>
    <div class="col-md-1">
        <a asp-action="Index" class="btn btn-light">Back</a>
    </div>
</div>
<hr />
<div class="list-header"></div>